// 八卦数据（经卦）
export const EightGaData = [
  {
    id: 1,
    name: '乾',
    symbol: '☰',
    gua_xing: '三阳',
    nature: '天',
    wuxing: '金',
    direction: '西北',
    family_relation: '父',
    attribute: '健',
    description: '天行健，君子以自强不息',
  },
  {
    id: 2,
    name: '坤',
    symbol: '☷',
    gua_xing: '三阴',
    nature: '地',
    wuxing: '土',
    direction: '西南',
    family_relation: '母',
    attribute: '顺',
    description: '地势坤，君子以厚德载物',
  },
  {
    id: 3,
    name: '震',
    symbol: '☳',
    gua_xing: '一阳二阴',
    nature: '雷',
    wuxing: '木',
    direction: '东',
    family_relation: '长男',
    attribute: '动',
    description: '洊雷，震，君子以恐惧修省',
  },
  {
    id: 4,
    name: '巽',
    symbol: '☴',
    gua_xing: '一阴二阳',
    nature: '风',
    wuxing: '木',
    direction: '东南',
    family_relation: '长女',
    attribute: '入',
    description: '随风，巽，君子以申命行事',
  },
  {
    id: 5,
    name: '坎',
    symbol: '☵',
    gua_xing: '一阳陷二阴',
    nature: '水',
    wuxing: '水',
    direction: '北',
    family_relation: '中男',
    attribute: '陷',
    description: '水洊至，习坎，君子以常德行',
  },
  {
    id: 6,
    name: '离',
    symbol: '☲',
    gua_xing: '一阴丽二阳',
    nature: '火',
    wuxing: '火',
    direction: '南',
    family_relation: '中女',
    attribute: '丽',
    description: '明两作，离，大人以继明照于四方',
  },
  {
    id: 7,
    name: '艮',
    symbol: '☶',
    gua_xing: '一阳二阴',
    nature: '山',
    wuxing: '土',
    direction: '东北',
    family_relation: '少男',
    attribute: '止',
    description: '兼山，艮，君子以思不出其位',
  },
  {
    id: 8,
    name: '兑',
    symbol: '☱',
    gua_xing: '一阴二阳',
    nature: '泽',
    wuxing: '金',
    direction: '西',
    family_relation: '少女',
    attribute: '悦',
    description: '丽泽，兑，君子以朋友讲习',
  },
];
