version: '1.0'
name: branch-pipeline
displayName: BranchPipeline

stages:
  - stage:
    name: compile
    displayName: 编译
    steps:
      - step: build@node
        name: build_node
        displayName: 安装 Node.js 20 和依赖
        nodeVersion: 20
        commands:
          - npm config set registry https://registry.npmmirror.com
          - npm install --legacy-peer-deps

      - step: build@android
        name: build_android
        displayName: 构建 APK
        jdkVersion: 17
        mavenVersion: 3.3.9
        gradleVersion: 8.2
        buildFile: ./android/build.gradle
        commands:
          - cd android
          - chmod +x gradlew
          - ./gradlew clean assembleRelease --no-daemon --stacktrace
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./android/app/build/outputs/apk/release/

      - step: publish@release_artifacts
        name: publish_release_artifacts
        displayName: 发布 Release
        dependArtifact: BUILD_ARTIFACT
        version: '1.2.2'
        autoIncrement: true

triggers:
  push:
    branches:
      exclude:
        - master
      include:
        - .*
