version: '1.0'
name: build-apk
displayName: build-apk
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-4e2b7e7e
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@gradle
        name: build_gradle
        displayName: Gradle 构建
        jdkVersion: '17'
        gradleVersion: '7.6'
        commands:
          - cd $WORKSPACE && chmod +x gradlew && ./gradlew assembleRelease --no-daemon --build-cache --parallel --no-watch-fs -Dorg.gradle.jvmargs="-Xmx4096m -XX:MaxMetaspaceSize=1024m"
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./target
        caches:
          - ~/.gradle/caches
        notify: []
        strategy:
          retry: '0'
