version: '1.0'
name: build-apk-20260409
displayName: 构建APK
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
stages:
  - name: build
    displayName: ''
    strategy: naturally
    trigger: auto
    steps:
      - step: build@gradle
        name: build_gradleap
        displayName: 构建签名 APK
        jdkVersion: '17'
        gradleVersion: '7.6'
        commands:
          - cd /root/workspace/joelinfo/divination-apk &&
          - npm install --legacy-peer-deps &&
          - cd android &&
          - chmod +x gradlew &&
          - ./gradlew clean assembleRelease -PstoreFile=${RELEASE_KEY} -PstorePassword=${STORE_PASSWORD} -PkeyAlias=${KEY_ALIAS} -PkeyPassword=${KEY_PASSWORD} --no-daemon
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - android/app/build/outputs/apk/release/*.apk
        caches:
          - ~/.gradle/caches
        notify: []
        strategy:
          retry: '0'
