version: '1.0'
name: build-apk
displayName: 构建签名APK
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - master
stages:
  - name: build
    displayName: 构建签名
    strategy: naturally
    trigger: auto
    steps:
      - step: build@gradle
        name: build_gradle
        displayName: 签名构建APK
        jdkVersion: '17'
        gradleVersion: '7.6'
        commands:
          - chmod +x gradlew && ./gradlew assembleRelease \
          - '  -PstoreFile=${RELEASE_KEY} \'
          - '  -PstorePassword=${STORE_PASSWORD} \'
          - '  -PkeyAlias=${KEY_ALIAS} \'
          - '  -PkeyPassword=${KEY_PASSWORD} \'
          - '  --no-daemon --build-cache --parallel --no-watch-fs -Dorg.gradle.jvmargs="-Xmx4096m -XX:MaxMetaspaceSize=1024m"'
        artifacts:
          - name: SIGNED_APK
            path:
              - app/build/outputs/apk/release/*.apk
        caches:
          - ~/.gradle/caches
        strategy:
          retry: '0'
