version: '1.0'
name: lingshu-build
displayName: lingshu-build
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-6f69ef59
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor:
      - joelinfo
    steps:
      - step: publish@release_artifacts
        name: publish_release_artifacts
        displayName: lingshu-paipan.apk
        dependArtifact: output
        version: 1.0.0.0
        autoIncrement: true
        notify: []
        strategy:
          retry: '0'
